{{- $ns := index .Values "_namespace" | default dict }}
{{- $tenantHost := index $ns "host" | default "" }}
{{- $tenantIngress := index $ns "ingress" | default .Release.Namespace }}
{{- $defaultHost := "" }}
{{- if $tenantHost }}
{{- $defaultHost = printf "%s.%s" .Release.Name $tenantHost }}
{{- end }}
{{- $inputHost := .Values.openwebui.ingress.host | default "" }}
{{- $ingressHost := $defaultHost }}
{{- if $inputHost }}
  {{- if and $tenantHost (not (contains "." $inputHost)) }}
    {{- $ingressHost = printf "%s.%s" $inputHost $tenantHost }}
  {{- else }}
    {{- $ingressHost = $inputHost }}
  {{- end }}
{{- end }}
{{- $ingressClass := .Values.openwebui.ingress.class | default $tenantIngress }}
{{- $cluster := index .Values "_cluster" | default dict }}
{{- $clusterDomain := index $cluster "cluster-domain" | default "cluster.local" }}
{{- $solver := index $cluster "solver" | default "http01" }}
{{- $clusterIssuer := index $cluster "issuer-name" | default "letsencrypt-prod" }}
{{- $defaultIngressAnnotations := dict "nginx.ingress.kubernetes.io/ssl-redirect" "true" "cert-manager.io/cluster-issuer" $clusterIssuer }}
{{- if eq $solver "http01" }}
  {{- $_ := set $defaultIngressAnnotations "acme.cert-manager.io/http01-ingress-ingressclassname" $ingressClass }}
{{- end }}
{{- $inputIngressAnnotations := .Values.openwebui.ingress.annotations | default dict }}
{{- $ingressAnnotations := merge $defaultIngressAnnotations $inputIngressAnnotations }}

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .Release.Name }}-system
spec:
  interval: 5m
  chart:
    spec:
      chart: open-webui
      version: 14.5.0
      sourceRef:
        kind: HelmRepository
        name: openwebui
        namespace: external-openwebui
  values:
    clusterDomain: {{ $clusterDomain | quote }}
    replicaCount: {{ .Values.openwebui.replicaCount }}
    service:
      type: {{ .Values.openwebui.service.type }}
    ingress:
      enabled: {{ .Values.openwebui.ingress.enabled }}
      class: {{ $ingressClass | quote }}
      host: {{ $ingressHost | quote }}
      tls: {{ .Values.openwebui.ingress.tls }}
      annotations:
{{ toYaml $ingressAnnotations | indent 8 }}
    persistence:
      enabled: {{ .Values.openwebui.persistence.enabled }}
      size: {{ .Values.openwebui.persistence.size | quote }}
    ollama:
      enabled: {{ .Values.openwebui.ollama.enabled }}
    pipelines:
      enabled: {{ .Values.openwebui.pipelines.enabled }}
