---
apiVersion: apps.cozystack.io/v1alpha1
kind: OpenWebUI
metadata:
  name: demo
  namespace: <tenant-namespace>
spec:
  openwebui:
    ingress:
      enabled: true
      class: <tenant-ingress-class>
      host: openwebui.example.com
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: <cluster-issuer>
        acme.cert-manager.io/http01-ingress-ingressclassname: <tenant-ingress-class>
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
    persistence:
      enabled: true
      size: 10Gi
    ollama:
      enabled: false
