openwebui:
  replicaCount: 1
  service:
    type: ClusterIP
  ingress:
    enabled: false
    class: ""
    host: ""
    tls: false
    annotations: {}
  persistence:
    enabled: true
    size: 10Gi
  ollama:
    enabled: false
  pipelines:
    enabled: true
